### PR TITLE
Delete lines belong to a merge conflict resolution

### PR DESCRIPTION
**Pull request by mar-bi**
It seems like there are extra lines left from a merge conflict resolution.
(The app is not running with these lines).

### CODE REVIEW

**Comment by HixOba** [comment]
I can see the lines, but i think there is a problem, most likely from my push. I uncommented the "import classnames...." line before i pushed because i fixed the issues for more than 2 hours before going to bed last night :(

Now it seems like the underlying problem has re-appeared lol

Allow me a few minutes to compare codes and see what i did wrong again before pushing last night

**Review by HixOba — COMMENTED** [review]
//import classnames from 'classnames';

Gave me problems all night so i commented it out to have some peace. But i realised it was an issue of no npm i classnames :)

we need it so all the lines:

======

className={classnames('form-control-form-control-lg', {
											'is-invalid': errors.name

=====

and similar ones like these can work properly

====

{errors.name && <div className="invalid-feedback">{errors.name}</div>}

====
can work properly

once i did this, it disappeared. now am not so sure what the problem is because it works fine in my LOCAL

any ideas?

===

i am working on logout, which is in same authActions.js file

so i will note the changes you have suggested here, and the conflicts and take care of them there. so once i finish on that logout branch, i will cancel this pull request, everything will be sorted in next push so u can review then

**Comment by mar-bi** [comment]
We can restore `classnames` back. I just deleted it as I thought it was unused import statement.
I was more surprised about double `render()` method and some extra characters. I thought that they appeared due to the merge conflict resolution.

**Comment by HixOba** [comment]
I noticed double render but wasnt sure where that came from too

**Pull request merged**
