### PR TITLE
Redux login

### PR DESCRIPTION
**Pull request by HixOba**
Login with redux, a few minor error messages

### CODE REVIEW

**Review by mar-bi — APPROVED** [review]
well done :+1:

**Comment by mar-bi** [comment]
I guess, you have got those conflicts because you merged my branch earlier.
Try to `pull` development branch (locally on your machine) and solve conflicts in your editor.
Then push your branch again. :smiley:

**Comment by HixOba** [comment]
I accidentally merged it actually. I was multi-tasking (bad idea!) and
merged a wrong one. I was meant to look at it but, it happens. My
understanding of what you did is remove the commented classnames and delete
it entirely, right?

If yes, it means i have to remove some error handling on the classnames in
the file so not sure if its such a good idea, is why i am slow to go with
it. What do you think?

I also saw it needs to go into navbar (classnames-based error handling), is
why i am still looking at both. So please bear with me while i think of how
to accomodate all.

Or do you have an alternative idea? Can we have a voice call?

**Comment by mar-bi** [comment]
I think you have a merge conflict here because I added a few packages to `package.json` and run `prettier` formatter. In my PR, that you have already merged I didn't touch `classnames`.

Update: If found that there are too many conflicts, you could just revert my merged PR and merge this PR first.
image
Also, if `prettier` and my config for `eslint` broke a lot of code, we can stop using it.

**Comment by HixOba** [comment]
Overtaken by subsequent events

**Pull request closed without merging**
